---
- name: Install Editors
  become: true
  package:
    name:
      - nano
      - vim-enhanced
    state: present
  register: _install
  until: _install is succeeded
  when: (ansible_os_family | lower) == 'redhat'
