---
- name: Enable yum proxy
  become: true
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ yum_proxy_url }}"
  when:
    - ansible_os_family == 'RedHat'
    - yum_proxy_manage and yum_proxy_url is defined
