---
# fastest mirror breaks proxies
- name: Disable yum fastestmirror plugin
  become: true
  ini_file:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    section: main
    option: enabled
    value: '0'
  when: ansible_os_family == 'RedHat'

# Always use protect base when multiple repos are in use
- name: Install yum protectbase plugin
  become: true
  package:
    name:
      - yum-plugin-protectbase
      - python-lxml
      - unzip
    state: present
  register: _install
  until: _install is succeeded
  when: ansible_os_family == 'RedHat'
