---

- name: install build tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ build_tools_packages }}"

- name: template rpmmacros
  become: false
  template:
    dest: /home/vagrant/.rpmmacros
    owner: vagrant
    group: vagrant
    mode: "u=rw,g=r,o="
    src: rpmmacros.j2

