---

- name: install build tools
  package:
    name: "{{ build_tools_packages }}"
    state: present
  register: _install
  until: _install is succeeded

- name: template rpmmacros
  become: false
  template:
    dest: /home/vagrant/.rpmmacros
    owner: vagrant
    group: vagrant
    mode: "u=rw,g=r,o="
    src: rpmmacros.j2
