---
- name: "Install EPEL Repo (CentOS)"
  become: true
  yum:
    name: epel-release
    state: present
  register: _install
  until: _install is succeeded
  when: (ansible_distribution | lower)== "centos"
